# 配置真实数据源
dataSource:
  common:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: nhsoft123
  # 配置第 1 个数据源
  ds0:
    jdbc-url: jdbc:mysql://localhost:3306/ds0
  # 配置第 2 个数据源
  ds1:
    jdbc-url: jdbc:mysql://localhost:3306/ds1

rules:
  # 配置分片规则
  - !SHARDING
    tables:
      # 配置 t_order 表规则
      t_order:
        actualDataNodes: ds${0..1}.t_order${0..15}
        # 配置分库策略
        databaseStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: database_inline
        # 配置分表策略
        tableStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: table_inline
        # 分布式序列策略
        keyGenerateStrategy:
          column: order_id
          keyGeneratorName: SNOWFLAKE

    # 配置分片算法
    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: ds${user_id % 2}
      table_inline:
        type: INLINE
        props:
          algorithm-expression: t_order${order_id % 16}

    # 分布式序列算法配置
    keyGenerators:
      SNOWFLAKE:
        type: SNOWFLAKE
        props:
          worker-id: 123


props:
  max-connections-size-per-query: 1
  sql-show: true #显示实际SQL